---
title: GOOS BioEco portal: move EOVs to keywords
date: "`r Sys.Date()`"
author: Pieter Provoost
#output: (function(...) { rmdformats::robobook(toc_depth = 3, pandoc_args = c("+RTS", "-K2000m", "-RTS"), ...) })
#output: bookdown::pdf_document2: latex_engine: lualatex
output:
  pdf_document:
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })  
---

This notebook backs up EOV/network links from GeoNode and restores them as keywords.

# Configuration

```{r warning = FALSE, message = FALSE}
old_host <- "geonode.goosocean.org"
new_host <- "geonode-dev.obis.org"
```

# Load packages

```{r warning = FALSE, message = FALSE}
library(dplyr)
library(DBI)
library(tidyr)
library(readr)
library(purrr)
library(glue)
library(RPostgres)
library(jsonlite)
library(stringr)
```

# Read links

```{r warning=FALSE, message=FALSE}
con_old <- DBI::dbConnect(RPostgres::Postgres(), dbname = "geonode", host = old_host, port = 5432, user = "geonode", password = "geonode")

layers_layer_eovs <- dbSendQuery(con, "select l.layer_id, e.id as eov_id, e.short_name from layers_layer_eovs l left join goos_eov e on l.eov_id = e.id") %>%
  dbFetch()

write.csv(layers_layer_eovs, file = "../data/layers_layer_eovs.csv", row.names = FALSE)
```

# Get keywords list

```{r warning=FALSE, message=FALSE}
tkeywords <- fromJSON(glue("https://{new_host}/api/v2/tkeywords?page_size=1000"))$tkeywords %>%
  filter(str_detect(about, "goosocean"))
```

# Update

Update `base_resourcebase_tkeywords` with columns `id`, `resourcebase_id`, `thesauruskeyword_id`.

```{r warning=FALSE, message=FALSE}
base_resourcebase_tkeywords <- layers_layer_eovs %>%
  left_join(tkeywords, by = c("short_name" = "alt_label")) %>%
  select(resourcebase_id = layer_id, thesauruskeyword_id = id)

con_new <- DBI::dbConnect(RPostgres::Postgres(), dbname = "geonode", host = new_host, port = 5432, user = "geonode", password = "geonode")
dbWriteTable(con_new, "base_resourcebase_tkeywords", base_resourcebase_tkeywords, overwrite = TRUE)
```



